#!/bin/sh

#
# Check for aws
#

if ! $(type aws > /dev/null); then
  echo -e "\najs: missing aws-cli (https://aws.amazon.com/cli)"
  exit 1
fi

#
# Check for jq
#

if ! $(type jq > /dev/null); then
  echo -e "\najs: missing jq (https://stedolan.github.io/jq)"
  exit 1
fi

#
# help funcion
#

help() {
  echo -e "\nusage: ajs <action> [paramenters]"
  echo -e "\nAvaliable actions"
  echo -e "   help                               show this message"
  echo -e "   version                            show script version"
  echo -e "   get <secret> [aws-parameters...]   get secret from secretsmanager to json file"
  echo -e "   put <secret> [aws-parameters...]   put secret from json file to secretsmanager"
  echo -e "Example: ajs get example --region eu-west-1"
}

#
# Getting first argument (lowercase)
#

action=${1,,}; shift

#
# Validate first argument
#

case ${action} in
  (-v|--version|version)
    echo -e "\najs/0.1.0"
    exit 0
    ;;
  (-h|--help|help)
    help
    exit 0
    ;;
  (get|put)
    ;;
  (*)
    help
    echo -e "\nOops: invalid action"
    exit 1
    ;;
esac

#
# Check secret name for action get and put
#

secret=${1}; shift

if [ -z ${secret} ]; then
  help
  echo -e "\nOops: you should specify a secret name"
  exit 1
fi

#
# AWS arguments
#

parameters=${@}

#
# Get secret action
#

if [ ${action} = "get" ]; then

  secrets=$(aws secretsmanager get-secret-value --secret-id ${secret} ${parameters})

  if [ "$?" -eq 0 ]; then
    echo "${secrets}" | jq -r .SecretString | jq > ${secret}.json
    echo -e "\nSecrets manager => ${secret}.json"
    exit 0
  else
    exit 1
  fi
fi

#
# Put secret action
#

if [ ${action} = "put" ]; then
  if [ ! -f "${PWD}/${secret}.json" ]; then
    echo -e "\nOops: ${secret}.json does not exist"
    exit 1
  fi

  aws secretsmanager put-secret-value --secret-id ${secret} \
    --secret-string $(jq -cM < ${secret}.json) ${parameters}

  if [ "$?" -eq 0 ]; then
    echo -e "\n${secret}.json => Secrets manager"
    exit 0
  else
    exit 1
  fi
fi

