#!/bin/sh

while [ "$#" -gt 0 ]; do
  case $1 in
    --help)
      echo "ajs"
      echo "  --help"
      echo "  --version"
      echo "  --profile <aws-profile>"
      echo "  --secret <secret-id>"
      echo "  --get, from secrets manager to json"
      echo "  --put, from json to secrets manager"
      echo "Author: Sabato Luca Guadagno <o0th@pm.me>"
      exit 0
      ;;
    --version)
      echo "ajs version 0.0.2"
      exit 0
      ;;
    --secret)
      secret="$2"
      shift
      shift
      ;;
    --profile)
      profile="$2"
      shift
      shift
      ;;
    --get)
      get="true"
      shift
      ;;
    --put)
      put="true"
      shift
      ;;
    *)
      shift
      ;;
  esac
done

if ! $(type aws > /dev/null); then
  echo "aws-cli is required"
  exit 1
fi

if ! $(type jq > /dev/null); then
  echo "jq is required"
  exit 1
fi

if [ -z "$secret" ]; then
  echo "--secret <secret-id> is required"
  exit 1
fi

if [ -z "$profile" ]; then
  profile="default"
fi

if [ -z "$get" ] && [ -z "$put" ]; then
  echo "--get or --put is required"
  exit 1
fi

if [ ! -z "$get" ]; then
  secrets=$(aws secretsmanager get-secret-value \
    --profile ${profile} --secret-id ${secret})
  if [ "$?" -eq 0 ]; then
    echo "${secrets}" | jq -r .SecretString | jq > ${secret}.json
    echo "Secrets manager => ${secret}.json"
    exit 0
  else
    exit 1
  fi
fi

if [ ! -z "$put" ]; then
  if [ ! -f "${PWD}/${secret}.json" ]; then
    echo "${secret}.json does not exist"
    exit 1
  fi
  aws secretsmanager put-secret-value \
    --profile ${profile} \
    --secret-id ${secret} \
    --secret-string $(jq -cM < ${secret}.json)
  if [ "$?" -eq 0 ]; then
    echo "${secret}.json => Secrets manager\n"
    exit 0
  else
    exit 1
  fi
fi
